### ISSUE TITLE
Das nennt man Magnitude, im Englischen gleich geschrieben ^^

### ISSUE THREAD

**Issue by DanHCraft** [facebamm/Se7en#2]
https://github.com/facebamm/Se7en/blob/3c9ae5ff943d15867e03c5c2fa1c21eab79749a9/Mathematic/Vector3f.cs#L66

**Comment by DanielBaumert** [comment]
Magnitude is technically more correct. I agree, but the amount is understandable

https://github.com/facebamm/Se7en/commit/09150a730438e2b990664c3fce4843e5035b2cf8#diff-ba2632e6364609cd3509a5d39199bf31R57
